name: Deploy to Google Cloud Run 

on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
        default: "dev"
      name:
        required: true
        type: string
      run_args:
        type: string
        default: ""
      deploy_on:
        required: true
        type: string # main หรือ tag
    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_REGION:
        required: true
      GCP_SA_KEY:
        required: true

jobs:
  deploy-cloudrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Deploy to Cloud Run
        run: |
          if [ "${{ inputs.deploy_on }}" = "main" ]; then
            TAG=main-${GITHUB_SHA::7}
            IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.name }}:$TAG"
          else
            TAG=${GITHUB_REF#refs/tags/}
            IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.name }}:$TAG"
          fi

          SERVICE_NAME=${{ inputs.env }}-${{ inputs.name }}

          gcloud secrets create $SERVICE_NAME --replication-policy="automatic" --data-file=<(echo -n "FirstStep=Initial") || true

          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region ${{ secrets.GCP_REGION }} \
            --set-env-vars DOTENV_PATH=/gsm/secret/dotenv \
            --set-secrets="/gsm/secret/dotenv=$SERVICE_NAME:latest" \
            --tag $TAG \
            --platform managed \
            --quiet ${{ inputs.run_args }}
